# .circleci/config.yml
version: 2.1
jobs:
  build:
    macos:
      xcode: 13.4
    resource_class: medium

    steps:
          - checkout
          - run: bundle install
          - run:
              name: Fastlane
              command: bundle exec fastlane $FASTLANE_LANE
          - store_artifacts:
              path: output
          - store_test_results:
              path: output/scan
              
workflows:
  build:
    jobs:
      - build
