# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 10.3.0
    resource_class: medium

workflows:
  build:
    jobs:
      - build
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build
